# Copyright (c) 2026, The Isaac Lab Arena Project Developers (https://github.com/isaac-sim/IsaacLab-Arena/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

env_name: marker_in_mug
external_yaml: ../scenes/workdesk.yaml
task:
  composition: atomic
  description: Put the whiteboard marker in the mug
  subtasks:
  - kind: PickAndPlaceTask
    params:
      pick_up_object: marker
      destination_location: ceramic_mug
      background_scene: maple_table_robolab
      episode_length_s: 20.0
