# Copyright (c) 2026, The Isaac Lab Arena Project Developers (https://github.com/isaac-sim/IsaacLab-Arena/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

env_name: mustard_above_raisin
external_yaml: ../scenes/mustard_raisin_box.yaml
task:
  composition: atomic
  description: Pick up the mustard bottle and place it on the raisin box.
  subtasks:
  - kind: PickAndPlaceTask
    params:
      pick_up_object: mustard_bottle
      destination_location: raisin_box
      background_scene: maple_table_robolab
      episode_length_s: 20.0
