# Copyright (c) 2025-2026, The Isaac Lab Arena Project Developers (https://github.com/isaac-sim/IsaacLab-Arena/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

"""Auto-generated by isaaclab_arena.llm_env_gen.

Task: Pick up the avocado from the table and place it into a bowl on the table, with distractor vegetables present.

NoTask is used as a placeholder — the initial scene graph is materialized
via add_relation() calls on each item, but there is no success predicate.
Swap NoTask for a real task (and implement the In relation) to wire up
goal checking.
"""

from __future__ import annotations

import argparse
from typing import TYPE_CHECKING

from isaaclab_arena.assets.register import register_environment
from isaaclab_arena_environments.example_environment_base import ExampleEnvironmentBase

if TYPE_CHECKING:
    from isaaclab_arena.environments.isaaclab_arena_environment import IsaacLabArenaEnvironment


@register_environment
class AvocadoPnPBowlTableEnvironment(ExampleEnvironmentBase):
    """Pick up the avocado from the table and place it into a bowl on the table, with distractor vegetables present."""

    name: str = "avocadoPnPbowltable"

    def get_env(self, args_cli: argparse.Namespace) -> "IsaacLabArenaEnvironment":
        from isaaclab_arena.environments.isaaclab_arena_environment import IsaacLabArenaEnvironment
        from isaaclab_arena.relations.relations import IsAnchor, On
        from isaaclab_arena.scene.scene import Scene
        from isaaclab_arena.tasks.no_task import NoTask
        from isaaclab_arena.utils.pose import Pose

        background = self.asset_registry.get_asset_by_name("table")()
        background.set_initial_pose(Pose(position_xyz=(0.5, 0.0, 0.0), rotation_xyzw=(0.0, 0.0, 0.7071068, 0.7071068)))
        background.add_relation(IsAnchor())
        ground_plane = self.asset_registry.get_asset_by_name("ground_plane")()
        ground_plane.set_initial_pose(Pose(position_xyz=(0.0, 0.0, -1.05)))
        light = self.asset_registry.get_asset_by_name("light")()

        # No kwargs — works for both no_embodiment and robot embodiments whose
        # optional flags (enable_cameras, etc.) default to safe values.
        embodiment = self.asset_registry.get_asset_by_name(args_cli.embodiment)()

        avocado_obj = self.asset_registry.get_asset_by_name("avocado01_fruits_veggies_robolab")()
        bowl_obj = self.asset_registry.get_asset_by_name("bowl_ycb_robolab")()
        broccoli_obj = self.asset_registry.get_asset_by_name("broccoli")()
        sweet_potato_obj = self.asset_registry.get_asset_by_name("sweet_potato")()
        red_bell_pepper_obj = self.asset_registry.get_asset_by_name("red_bell_pepper_objaverse_robolab")()

        avocado_obj.add_relation(On(background, clearance_m=0.02))
        bowl_obj.add_relation(On(background, clearance_m=0.02))
        broccoli_obj.add_relation(On(background, clearance_m=0.02))
        sweet_potato_obj.add_relation(On(background, clearance_m=0.02))
        red_bell_pepper_obj.add_relation(On(background, clearance_m=0.02))

        scene = Scene(assets=[background, ground_plane, light, avocado_obj, bowl_obj, broccoli_obj, sweet_potato_obj, red_bell_pepper_obj])

        return IsaacLabArenaEnvironment(
            name=self.name,
            embodiment=embodiment,
            scene=scene,
            task=NoTask(),
        )

    @staticmethod
    def add_cli_args(parser: argparse.ArgumentParser) -> None:
        parser.add_argument("--embodiment", type=str, default="franka_ik")
