# Copyright (c) 2025-2026, The Isaac Lab Arena Project Developers (https://github.com/isaac-sim/IsaacLab-Arena/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

"""Auto-generated by isaaclab_arena.llm_env_gen.

Task: Pick up the avocado from the table and place it into a bowl on the table, with distractor vegetables present.

Task wiring: PickAndPlaceTask: pick_up=avocado, destination=bowl
"""

from __future__ import annotations

import argparse
from typing import TYPE_CHECKING

from isaaclab_arena.assets.register import register_environment
from isaaclab_arena_environments.example_environment_base import ExampleEnvironmentBase

if TYPE_CHECKING:
    from isaaclab_arena.environments.isaaclab_arena_environment import IsaacLabArenaEnvironment


@register_environment
class AvocadoPnPBowlTableEnvironment(ExampleEnvironmentBase):
    """Pick up the avocado from the table and place it into a bowl on the table, with distractor vegetables present."""

    name: str = "avocadoPnPbowltable"

    def get_env(self, args_cli: argparse.Namespace) -> "IsaacLabArenaEnvironment":
        from isaaclab_arena.assets.object_base import ObjectType
        from isaaclab_arena.assets.object_reference import ObjectReference
        from isaaclab_arena.environments.isaaclab_arena_environment import IsaacLabArenaEnvironment
        from isaaclab_arena.relations.relations import IsAnchor, On, PositionLimits
        from isaaclab_arena.scene.scene import Scene
        from isaaclab_arena.tasks.pick_and_place_task import PickAndPlaceTask
        from isaaclab_arena.utils.pose import Pose

        background = self.asset_registry.get_asset_by_name("table")()
        background.set_initial_pose(Pose(position_xyz=(0.5, 0.0, 0.0), rotation_xyzw=(0.0, 0.0, 0.7071068, 0.7071068)))
        ground_plane = self.asset_registry.get_asset_by_name("ground_plane")()
        ground_plane.set_initial_pose(Pose(position_xyz=(0.0, 0.0, -1.05)))
        light = self.asset_registry.get_asset_by_name("light")()

        # Tabletop anchor — tabletop anchor = background (background); PositionLimits derived from get_world_bounding_box().
        background.add_relation(IsAnchor())

        # No kwargs — works for both no_embodiment and robot embodiments whose
        # optional flags (enable_cameras, etc.) default to safe values.
        embodiment = self.asset_registry.get_asset_by_name(args_cli.embodiment)()

        avocado_obj = self.asset_registry.get_asset_by_name("avocado01_fruits_veggies_robolab")()
        bowl_obj = self.asset_registry.get_asset_by_name("bowl_ycb_robolab")()
        broccoli_obj = self.asset_registry.get_asset_by_name("broccoli")()
        sweet_potato_obj = self.asset_registry.get_asset_by_name("sweet_potato")()
        red_bell_pepper_obj = self.asset_registry.get_asset_by_name("red_bell_pepper_objaverse_robolab")()

        # Runtime-derived XY footprint from the tabletop bbox — no
        # hardcoded bounds, works across tables of any size. The
        # bbox stores (N, 3) tensors; we squeeze to plain floats
        # for the first env since PositionLimits takes scalars and
        # the tabletop is static across envs.
        _tbl_bbox = background.get_world_bounding_box()
        _tbl_min_xyz = [float(_tbl_bbox.min_point[0, i]) for i in range(3)]
        _tbl_max_xyz = [float(_tbl_bbox.max_point[0, i]) for i in range(3)]
        _tbl_margin = 0.05

        avocado_obj.add_relation(On(background, clearance_m=0.02))
        avocado_obj.add_relation(PositionLimits(
            x_min=_tbl_min_xyz[0] + _tbl_margin,
            x_max=_tbl_max_xyz[0] - _tbl_margin,
            y_min=_tbl_min_xyz[1] + _tbl_margin,
            y_max=_tbl_max_xyz[1] - _tbl_margin,
        ))
        bowl_obj.add_relation(On(background, clearance_m=0.02))
        bowl_obj.add_relation(PositionLimits(
            x_min=_tbl_min_xyz[0] + _tbl_margin,
            x_max=_tbl_max_xyz[0] - _tbl_margin,
            y_min=_tbl_min_xyz[1] + _tbl_margin,
            y_max=_tbl_max_xyz[1] - _tbl_margin,
        ))
        broccoli_obj.add_relation(On(background, clearance_m=0.02))
        broccoli_obj.add_relation(PositionLimits(
            x_min=_tbl_min_xyz[0] + _tbl_margin,
            x_max=_tbl_max_xyz[0] - _tbl_margin,
            y_min=_tbl_min_xyz[1] + _tbl_margin,
            y_max=_tbl_max_xyz[1] - _tbl_margin,
        ))
        sweet_potato_obj.add_relation(On(background, clearance_m=0.02))
        sweet_potato_obj.add_relation(PositionLimits(
            x_min=_tbl_min_xyz[0] + _tbl_margin,
            x_max=_tbl_max_xyz[0] - _tbl_margin,
            y_min=_tbl_min_xyz[1] + _tbl_margin,
            y_max=_tbl_max_xyz[1] - _tbl_margin,
        ))
        red_bell_pepper_obj.add_relation(On(background, clearance_m=0.02))
        red_bell_pepper_obj.add_relation(PositionLimits(
            x_min=_tbl_min_xyz[0] + _tbl_margin,
            x_max=_tbl_max_xyz[0] - _tbl_margin,
            y_min=_tbl_min_xyz[1] + _tbl_margin,
            y_max=_tbl_max_xyz[1] - _tbl_margin,
        ))

        scene = Scene(assets=[background, ground_plane, light, avocado_obj, bowl_obj, broccoli_obj, sweet_potato_obj, red_bell_pepper_obj])

        # goal_added (enforced by PickAndPlaceTask success predicate):  in(avocado, bowl)
        # goal_removed (implicitly negated when the pick succeeds):  on(avocado, table)

        return IsaacLabArenaEnvironment(
            name=self.name,
            embodiment=embodiment,
            scene=scene,
            task=PickAndPlaceTask(
                pick_up_object=avocado_obj,
                destination_location=bowl_obj,
                background_scene=background,
                episode_length_s=20.0,
                task_description='Pick up the avocado from the table and place it into a bowl on the table, with distractor vegetables present.',
            ),
        )

    @staticmethod
    def add_cli_args(parser: argparse.ArgumentParser) -> None:
        parser.add_argument("--embodiment", type=str, default="franka_ik")
