"""GoalSpec — structured task definition consumed by planner, CuRobo, and evaluator.

This is the single source of truth for a generated task. Both the JSON
output (for A* planner + CuRobo) and the Python TaskBase class (for
Isaac Lab runtime) are derived from this dataclass.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any


@dataclass
class GoalRelation:
    """A desired spatial relation between objects after task completion.

    Consumed by the A* symbolic planner to decompose into action sequences,
    and by CuRobo to compute target poses.
    """
    predicate: str          # e.g. "in_container", "on_top", "left_of"
    object: str             # Object to manipulate
    target: str             # Target object/surface
    params: dict = field(default_factory=dict)


@dataclass
class SuccessCondition:
    """A runtime predicate check for task termination.

    Evaluated during Isaac Lab simulation to determine if the task succeeded.
    """
    predicate: str          # e.g. "object_in_container", "object_on_top"
    args: dict = field(default_factory=dict)


@dataclass
class SubtaskSpec:
    """A subtask for progress tracking (graded scoring).

    Each subtask defines stages with fractional scores.
    """
    type: str               # e.g. "pick_and_place", "open_close", "pick"
    object: str             # Object being manipulated
    target: str = ""        # Target (container, surface, appliance)
    stages: list[str] = field(default_factory=lambda: ["grab", "lift", "move", "drop", "verify"])


@dataclass
class ObjectState:
    """Initial state of an object in the scene."""
    position: tuple[float, float, float]
    rotation: tuple[float, float, float, float] = (1.0, 0.0, 0.0, 0.0)
    on: str = "table"
    dims: tuple[float, float, float] | None = None


@dataclass
class GoalSpec:
    """Complete task specification — the dual-output source of truth.

    Generated by the LLM, validated, then used to produce:
    1. task.json — for A* planner + CuRobo motion planner
    2. task_class.py — for Isaac Lab runtime evaluation
    """
    task_name: str
    instruction: str
    scene: str                          # Scene USD filename
    category: str                       # RQA category
    difficulty: str                     # simple / moderate / complex

    contact_objects: list[str]          # Objects the robot interacts with
    initial_state: dict[str, ObjectState] = field(default_factory=dict)
    goal_relations: list[GoalRelation] = field(default_factory=list)
    success_conditions: list[SuccessCondition] = field(default_factory=list)
    subtasks: list[SubtaskSpec] = field(default_factory=list)

    episode_length_s: int = 60
    attributes: list[str] = field(default_factory=list)
    ik_feasible: bool | None = None  # None = not checked, True/False = checked

    def to_dict(self) -> dict[str, Any]:
        """Convert to JSON-serializable dict."""
        d = asdict(self)
        for name, state in d.get("initial_state", {}).items():
            state["position"] = list(state["position"])
            if state.get("rotation"):
                state["rotation"] = list(state["rotation"])
            if state.get("dims"):
                state["dims"] = list(state["dims"])
        return d

    def save_json(self, output_dir: str | Path) -> Path:
        """Save task spec to JSON file."""
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        path = output_dir / f"{self.task_name}.json"
        with open(path, "w") as f:
            json.dump(self.to_dict(), f, indent=2)
        return path

    @classmethod
    def from_json(cls, json_path: str | Path) -> GoalSpec:
        """Load task spec from JSON file."""
        with open(json_path) as f:
            d = json.load(f)

        initial_state = {}
        for name, state in d.get("initial_state", {}).items():
            initial_state[name] = ObjectState(
                position=tuple(state["position"]),
                rotation=tuple(state.get("rotation", (1, 0, 0, 0))),
                on=state.get("on", "table"),
                dims=tuple(state["dims"]) if state.get("dims") else None,
            )

        return cls(
            task_name=d["task_name"],
            instruction=d["instruction"],
            scene=d["scene"],
            category=d["category"],
            difficulty=d["difficulty"],
            contact_objects=d["contact_objects"],
            initial_state=initial_state,
            goal_relations=[GoalRelation(**r) for r in d.get("goal_relations", [])],
            success_conditions=[SuccessCondition(**c) for c in d.get("success_conditions", [])],
            subtasks=[SubtaskSpec(**s) for s in d.get("subtasks", [])],
            episode_length_s=d.get("episode_length_s", 60),
            attributes=d.get("attributes", []),
        )
