# Copyright (c) 2025-2026, The Isaac Lab Arena Project Developers (https://github.com/isaac-sim/IsaacLab-Arena/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

"""Generate a registered ArenaEnvironment file from a ResolvedScene.

Takes the initial_scene_graph from a resolved scene and writes a Python
module that instantiates the background + embodiment + items, applies the
initial relations, and wires them into an IsaacLabArenaEnvironment with
NoTask (the null task used for non-goal-driven scene walkthroughs).

The `in` / goal relations are intentionally NOT materialized here — NoTask
has no success predicate, and there is no In relation class yet (see the
TODO in isaaclab_arena.relations.relations). To wire up goal checking,
swap NoTask for a real task and implement the In relation first.
"""

from __future__ import annotations

import re
from pathlib import Path

from .resolver import ResolvedScene
from .schema import SceneSpec

# Relation kinds the writer knows how to translate into Arena `add_relation`
# calls. Anything else is emitted as a commented-out placeholder.
_SUPPORTED_INITIAL_KINDS = {"on"}


def _safe_var(name: str) -> str:
    v = re.sub(r"[^a-zA-Z0-9_]", "_", name).strip("_")
    if not v:
        return "obj"
    if v[0].isdigit():
        v = "_" + v
    return v


def _slug(s: str) -> str:
    v = re.sub(r"[^a-z0-9]+", "_", s.lower()).strip("_")
    return (v[:40] if v else "llm_env").rstrip("_")


def _class_name(slug: str) -> str:
    return "".join(part.capitalize() for part in slug.split("_") if part) + "Environment"


def write_env(resolved: ResolvedScene, spec: SceneSpec, out_path: str | Path) -> Path:
    """Render the env module to ``out_path`` and return the final path."""
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    env_slug = _slug(spec.task_description)
    class_name = _class_name(env_slug)

    item_vars: dict[str, str] = {}  # instance_name -> python var
    for instance_name in resolved.items:
        item_vars[instance_name] = f"{_safe_var(instance_name)}_obj"

    body = _render_module(
        class_name=class_name,
        env_name=env_slug,
        task_description=spec.task_description,
        background_name=resolved.background.name if resolved.background else spec.background,
        embodiment_default=resolved.embodiment_name,
        items=[(item_vars[n], cls.name, n) for n, cls in resolved.items.items()],
        initial_relations=_render_relations(resolved, spec, item_vars),
        asset_list_src=["background", "ground_plane", "light", *item_vars.values()],
    )

    out_path.write_text(body)
    return out_path


def _render_relations(
    resolved: ResolvedScene, spec: SceneSpec, item_vars: dict[str, str]
) -> list[str]:
    """Translate initial_scene_graph into add_relation call source lines."""
    lines: list[str] = []
    for rel in resolved.initial_scene_graph:
        subject_var = item_vars.get(rel["subject"])
        target_name = rel["target"]

        if subject_var is None:
            lines.append(f"        # SKIPPED (unknown subject {rel['subject']!r}): {rel}")
            continue

        if rel["kind"] == "on":
            target_var = "background" if target_name == spec.background else item_vars.get(target_name)
            if target_var is None:
                lines.append(f"        # SKIPPED (unknown target {target_name!r}): {rel}")
                continue
            lines.append(f"        {subject_var}.add_relation(On({target_var}, clearance_m=0.02))")
        else:
            lines.append(
                f"        # TODO({rel['kind']}): no generator support yet for this relation kind. raw={rel}"
            )
    return lines


def _render_module(
    *,
    class_name: str,
    env_name: str,
    task_description: str,
    background_name: str,
    embodiment_default: str,
    items: list[tuple[str, str, str]],
    initial_relations: list[str],
    asset_list_src: list[str],
) -> str:
    item_decls = "\n".join(
        f'        {var} = self.asset_registry.get_asset_by_name("{asset}")(instance_name="{inst}")'
        for var, asset, inst in items
    )
    relations_src = "\n".join(initial_relations) if initial_relations else "        # (no initial relations)"
    asset_list = ", ".join(asset_list_src)

    return f'''# Copyright (c) 2025-2026, The Isaac Lab Arena Project Developers (https://github.com/isaac-sim/IsaacLab-Arena/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

"""Auto-generated by isaaclab_arena_examples.llm_env_gen.

Task: {task_description}

NoTask is used as a placeholder — the initial scene graph is materialized
via add_relation() calls on each item, but there is no success predicate.
Swap NoTask for a real task (and implement the In relation) to wire up
goal checking.
"""

from __future__ import annotations

import argparse
from typing import TYPE_CHECKING

from isaaclab_arena.assets.register import register_environment
from isaaclab_arena_environments.example_environment_base import ExampleEnvironmentBase

if TYPE_CHECKING:
    from isaaclab_arena.environments.isaaclab_arena_environment import IsaacLabArenaEnvironment


@register_environment
class {class_name}(ExampleEnvironmentBase):
    """{task_description}"""

    name: str = "{env_name}"

    def get_env(self, args_cli: argparse.Namespace) -> "IsaacLabArenaEnvironment":
        from isaaclab_arena.environments.isaaclab_arena_environment import IsaacLabArenaEnvironment
        from isaaclab_arena.relations.relations import On
        from isaaclab_arena.scene.scene import Scene
        from isaaclab_arena.tasks.no_task import NoTask

        background = self.asset_registry.get_asset_by_name("{background_name}")()
        ground_plane = self.asset_registry.get_asset_by_name("ground_plane")()
        light = self.asset_registry.get_asset_by_name("light")()

        embodiment = self.asset_registry.get_asset_by_name(args_cli.embodiment)(
            enable_cameras=args_cli.enable_cameras,
        )

{item_decls}

{relations_src}

        scene = Scene(assets=[{asset_list}])

        return IsaacLabArenaEnvironment(
            name=self.name,
            embodiment=embodiment,
            scene=scene,
            task=NoTask(),
        )

    @staticmethod
    def add_cli_args(parser: argparse.ArgumentParser) -> None:
        parser.add_argument("--embodiment", type=str, default="{embodiment_default}")
'''
